# -*- mode: ruby -*-
# vi: set ft=ruby :

disk = '/home/javier/VMs/VirtualBox/HDDs/docker_vm1_1.vmdk'

Vagrant.configure("2") do |config|
  config.vm.box = "moconinja/debian-lvm-docker"
  config.vm.network "private_network", ip: "192.168.60.10"
  config.vm.provider "virtualbox" do |vb|
    unless File.exist?(disk)
      vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 5 * 1024]
    end
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end
end
